name: MOxUnit
on: [push, pull_request]
jobs:
  run-moxunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@v1.1
        with:
          tests: tests
          src: src
